processes and signals

diff --git a/0x05-processes_and_signals/5-dont_stop_me_now b/0x05-processes_and_signals/5-dont_stop_me_now
--- a/0x05-processes_and_signals/5-dont_stop_me_now
+++ b/0x05-processes_and_signals/5-dont_stop_me_now
@@ -1,6 +1,5 @@
 #!/usr/bin/env bash
-# stop 'To infinity and beyond' indefinitely,
-while "true"
-do
-	kill
-done
+# target process '4-to_infinity_and_beyond'
+if [[ -z "$target_pid" ]]; then
+  echo "Target process not found."
+  exit 1
