processes and signals

diff --git a/0x05-processes_and_signals/6-stop_me_if_you_can b/0x05-processes_and_signals/6-stop_me_if_you_can
--- a/0x05-processes_and_signals/6-stop_me_if_you_can
+++ b/0x05-processes_and_signals/6-stop_me_if_you_can
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
-# stop 'To infinity and beyond' indefinitely,
-if 'To infinity and beyond'
-	echo 'not found'
-exit 
+# target pid '4-to_infinity_and_beyond'
+if [[ -z "$target_pid" ]]; then
+echo "Target process not found."
+exit 1
 fi
